version: "3.9"
services:
  server_app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    container_name: fast_api
    stop_signal: SIGKILL
    depends_on:
      - database
      - redis
    volumes:
      - ../logs/:/logs
    ports:
      - "5000:5000"
    env_file:
      - ../environments/.env

  database:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../environments/.env
    volumes:
      - ../postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    restart: always
    stop_signal: SIGKILL
    env_file:
      - ../environments/.env
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: celery_app
    command: celery --app=src.celery_init:celery_app worker --loglevel=info --logfile=../logs/celery.log
    volumes:
      - ../logs/:/logs
    env_file:
      - ../environments/.env
    depends_on:
      - redis