version: "3.9"
services:
  server_app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    container_name: fast_api
    stop_signal: SIGKILL
    volumes:
      - ../logs/:/logs
    ports:
      - "5000:5000"
    env_file:
      - ../environments/.env

  database:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../environments/.env
    volumes:
      - ../postgres/data:/var/lib/postgresql/data