name: CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    types: [opened, reopened, edited]
    paths-ignore:
      - '.github/workflows/*'
jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: mypy
      run: python -m poetry run mypy src/
    - name: isort
      run: python -m poetry run isort --check-only src/
    - name: black
      run: python -m poetry run black --check --diff src/
    - name: flake8
      run: python -m poetry run flake8 src/
    - name: pytest
      run: python -m poetry run pytest tests/
